- name: mongodb setup
  hosts: all
  become: yes
  tasks:
    - name: Copy mongod repo file
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo
    
    - name: Install mongodb package
      ansible.builtin.yum:
        name: mongodb-org
        state: latest

    - name: Change the IP
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start and enable the mongod service
      ansible.builtin.systemd:
        name: mongod  
        state: started
        enabled: yes
